### PR TITLE
Api gateway

### PR DESCRIPTION
**Pull request by Kyeg**

### CODE REVIEW

**Comment by Kyeg** [comment]
All the unit tests of api-gateway can pass.

```
> rake spec:all
Run options: --seed 21107

# Running:

....

Finished in 0.017126s, 233.5630 runs/s, 817.4705 assertions/s.

4 runs, 14 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for RSpec to /Users/kyeg_logos_mac/GitHub_Box/app-mind-map/coverage. 144 / 226 LOC (63.72%) covered.
```

**Comment by Kyeg** [comment]
But there are two problems in current unit test. 

First problem is this test: https://github.com/KED-2020/app-mind-map/blob/402b560df1a14e21fd958a54fa33b85e17694fd2/spec/tests_unit/mind_map_api_spec.rb#L13
Because we do not have "POST inboxes/" api, so now can only pass this test by manually adding inbox in the api backend.

**Comment by Kyeg** [comment]
The second problem is this test:
https://github.com/KED-2020/app-mind-map/blob/402b560df1a14e21fd958a54fa33b85e17694fd2/spec/tests_unit/mind_map_api_spec.rb#L57

As following example:
```
> http post "localhost:9000/api/v1/favorites/documents?html_url=https://github.com/derrxb/derrxb"

HTTP/1.1 201 Created
Content-Length: 319
Content-Type: application/json

{
    "description": "My space online for my photography and software development thoughts",
    "html_url": "https://github.com/derrxb/derrxb",
    "links": [
        {
            "href": "http://localhost:9090/api/v1/inboxes/derrxb",
            "rel": "self"
        }
    ],
    "name": "derrxb",
    "origin_id": 165785822,
    "topics": [
        {
            "name": "blog"
        },
        {
            "name": "photography"
        },
        {
            "name": "portfolio"
        }
    ]
}
```
Because our current POST api of document do not return the id of this document, so I cannot GET this document in this test.

Should we 
1. return the document `id` from the POST
2. or get the document based on other parameter for example by `html_url` or `origin_id`?

**Comment by Kyeg** [comment]
Like unit tests, similar problems occur in service tests.

https://github.com/KED-2020/app-mind-map/blob/ee8ef00f1764dff2d17f192cf15563ef2b36f8cb/spec/tests_service/get_inbox_spec.rb#L8

https://github.com/KED-2020/app-mind-map/blob/ee8ef00f1764dff2d17f192cf15563ef2b36f8cb/spec/tests_service/get_document_spec.rb#L8

**Review by derrxb — APPROVED** [review]

**Comment by derrxb** [comment]
Okay, I can fix the hard coding issue by adding the required endpoints

**Pull request merged**
